// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdm6aEDaYB7bgiOB4siFWJUr7qMYpogbI',
    appId: '1:116893640761:web:9bf92a8f2116c1fc0485e8',
    messagingSenderId: '116893640761',
    projectId: 'on-campus-d0cb6',
    authDomain: 'on-campus-d0cb6.firebaseapp.com',
    storageBucket: 'on-campus-d0cb6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFrDM-eEEexV0DzxWRvLV8KCtsXasaka8',
    appId: '1:116893640761:android:9a539eb04e9d170c0485e8',
    messagingSenderId: '116893640761',
    projectId: 'on-campus-d0cb6',
    storageBucket: 'on-campus-d0cb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1bGYKSxhZKgl-xKSTuPpsa6LAdZI_U8o',
    appId: '1:116893640761:ios:a4b4ccb755a6da040485e8',
    messagingSenderId: '116893640761',
    projectId: 'on-campus-d0cb6',
    storageBucket: 'on-campus-d0cb6.firebasestorage.app',
    androidClientId: '116893640761-01nbk5ala631bacv22kak701mem66sip.apps.googleusercontent.com',
    iosClientId: '116893640761-hivl32mu2ohr9fanbb791immrutkeb11.apps.googleusercontent.com',
    iosBundleId: 'com.example.onCampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1bGYKSxhZKgl-xKSTuPpsa6LAdZI_U8o',
    appId: '1:116893640761:ios:a4b4ccb755a6da040485e8',
    messagingSenderId: '116893640761',
    projectId: 'on-campus-d0cb6',
    storageBucket: 'on-campus-d0cb6.firebasestorage.app',
    androidClientId: '116893640761-01nbk5ala631bacv22kak701mem66sip.apps.googleusercontent.com',
    iosClientId: '116893640761-hivl32mu2ohr9fanbb791immrutkeb11.apps.googleusercontent.com',
    iosBundleId: 'com.example.onCampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdm6aEDaYB7bgiOB4siFWJUr7qMYpogbI',
    appId: '1:116893640761:web:9bf92a8f2116c1fc0485e8',
    messagingSenderId: '116893640761',
    projectId: 'on-campus-d0cb6',
    authDomain: 'on-campus-d0cb6.firebaseapp.com',
    storageBucket: 'on-campus-d0cb6.firebasestorage.app',
  );

}